on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - run: pnpm --version && pnpm i
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          corepack enable
          pnpm --version
